# Generated by Django 5.2 on 2025-04-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='longetude',
            new_name='longitude',
        ),
    ]
